<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>org.dromara</groupId>
        <artifactId>ruoyi-modules</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>ruoyi-system</artifactId>

    <description>
        ruoyi-system系统模块
    </description>

    <dependencies>

        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>ruoyi-common-nacos</artifactId>
        </dependency>

        <!-- RuoYi Common Log -->
        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>ruoyi-common-log</artifactId>
        </dependency>

        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>ruoyi-common-service-impl</artifactId>
        </dependency>

        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>ruoyi-common-doc</artifactId>
        </dependency>

        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>ruoyi-common-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>ruoyi-common-mybatis</artifactId>
        </dependency>

        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>ruoyi-common-dubbo</artifactId>
        </dependency>

        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>ruoyi-common-seata</artifactId>
        </dependency>

        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>ruoyi-common-idempotent</artifactId>
        </dependency>

        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>ruoyi-common-tenant</artifactId>
        </dependency>

        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>ruoyi-common-security</artifactId>
        </dependency>

        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>ruoyi-common-translation</artifactId>
        </dependency>

        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>ruoyi-common-sensitive</artifactId>
        </dependency>

        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>ruoyi-common-encrypt</artifactId>
        </dependency>

        <!-- RuoYi Api System -->
        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>ruoyi-api-system</artifactId>
        </dependency>

        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>ruoyi-api-resource</artifactId>
        </dependency>

        <!-- RuoYi Api System -->
        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>ruoyi-api-workflow</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-amqp</artifactId>
        </dependency>

        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>ruoyi-common-json</artifactId>
        </dependency>

        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>ruoyi-api-websocket</artifactId>
        </dependency>

    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>3.2.0</version>
                <dependencies>
                    <dependency>
                        <groupId>com.yworks</groupId>
                        <artifactId>yguard</artifactId>
                        <version>${yguard.version}</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <id>obfuscate</id>
                        <configuration>
                            <target>
                                <property name="project.build.prefix" value="${project.build.directory}/${project.build.finalName}"/>
                                <property name="project.jar" value="${project.build.prefix}.jar"/>
                                <available file="${project.jar}" property="project.jar.exists"/>
                                <fail unless="project.jar.exists">${project.jar} does not exist.</fail>

                                <!-- 备份原始jar -->
                                <property name="project.jar.unobf" value="${project.build.prefix}_unobf.jar"/>
                                <move file="${project.jar}" tofile="${project.jar.unobf}" verbose="true"/>

                                <!-- 提取应用classes用于混淆 -->
                                <property name="project.classes.unobf" value="${project.build.prefix}_classes_unobf.jar"/>
                                <jar destfile="${project.classes.unobf}">
                                    <mappedresources>
                                        <zipfileset src="${project.jar.unobf}">
                                            <include name="BOOT-INF/classes/**"/>
                                        </zipfileset>
                                        <mapper type="glob" from="BOOT-INF/classes/*" to="*"/>
                                    </mappedresources>
                                </jar>

                                <!-- 混淆应用classes -->
                                <property name="runtime.classpath" refid="maven.runtime.classpath"/>
                                <property name="project.classes.obf" value="${project.build.prefix}_classes_obf.jar"/>
                                <taskdef name="yguard" classname="com.yworks.yguard.YGuardTask" classpathref="maven.plugin.classpath"/>
                                <yguard>
                                    <inoutpair in="${project.classes.unobf}" out="${project.classes.obf}"/>

                                    <externalclasses>
                                        <pathelement path="${runtime.classpath}"/>
                                    </externalclasses>

                                    <rename mainclass="org.dromara.system.RuoYiSystemApplication" logfile="${project.build.directory}/${project.build.finalName}_renamelog.xml">
                                        <map>
                                            <class name="org.dromara.system.service.impl.SysConfigServiceImpl" map="aa1"/>
                                            <class name="org.dromara.system.service.impl.SysDeptServiceImpl" map="aa2"/>
                                            <class name="org.dromara.system.service.impl.SysDictDataServiceImpl" map="aa3"/>
                                            <class name="org.dromara.system.service.impl.SysDictTypeServiceImpl" map="aa4"/>
                                            <class name="org.dromara.system.service.impl.SysLogininforServiceImpl" map="aa5"/>
                                            <class name="org.dromara.system.service.impl.SysMenuServiceImpl" map="aa6"/>
                                            <class name="org.dromara.system.service.impl.SysUserServiceImpl" map="aa7"/>
                                        </map>
                                        <keep>
                                            <class classes="public" methods="public" fields="none">
                                                <patternset>
                                                    <include name="org.dromara.system.api.**"/>
                                                    <include name="org.dromara.system.domain.**"/>
                                                    <include name="org.dromara.system.mapper.*"/>
                                                    <include name="org.dromara.system.controller.*"/>
                                                </patternset>
                                            </class>
                                        </keep>
                                    </rename>
                                </yguard>

                                <!-- 重新打包jar -->
                                <zip compress="false" destfile="${project.jar}">
                                    <zipfileset src="${project.jar.unobf}">
                                        <include name="**"/>
                                        <exclude name="BOOT-INF/classes/**"/>
                                    </zipfileset>
                                    <zipfileset src="${project.classes.obf}" prefix="BOOT-INF/classes">
                                        <include name="**"/>
                                        <exclude name="META-INF/**"/>
                                    </zipfileset>
                                </zip>
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
